name: Generate Outputs
on:
  push:
    paths:
      - dic/*.y*ml
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Generate outputs
      run: python3 generate.py
    - name: Commit to main
      run: |
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git add outputs/*
        git commit -m "Automated updated output files" 
        git push -f origin main

#     - name: Create Pull Request
#       uses: peter-evans/create-pull-request@v4.2.2
#       with:
#         delete-branch: true
#         title: "Updated output files"
#         labels: |
#           automated
