name: Generate Outputs
on:
  push:
    paths:
      - dic/*.y*ml
  workflow_dispatch:
    
jobs:
  generate_outputs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Update Software Dictionary
      run: python3 generate_software_names_dic.py
    - name: Generate outputs
      run: python3 generate.py
    - name: Commit to main
      run: |
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git add outputs/*
        git commit -m "Automated generation of outputs" 
        git push -f origin main
